/**
 * Small, valid PDFs, built by hand.
 *
 * Handwritten rather than generated by a library, so the tests do not depend on
 * a PDF writer whose own output might drift, and so a PDF with *no* text layer
 * can be produced deliberately - which is the case that matters here and the
 * one most writers make hard to construct.
 *
 * Offsets are computed so the xref table is correct and strict parsers are
 * satisfied.
 */

/** A PDF containing the given lines as a real text layer. */
export function pdfWithText(lines: string[], pages = 1): Uint8Array {
    const objects: string[] = [];

    const pageIds = Array.from({ length: pages }, (_, i) => 4 + i * 2);
    objects.push(`<</Type/Catalog/Pages 2 0 R>>`);
    objects.push(`<</Type/Pages/Kids[${pageIds.map((id) => `${id} 0 R`).join(" ")}]/Count ${pages}>>`);
    objects.push(`<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>`);

    for (let page = 0; page < pages; page++) {
        const content =
            `BT /F1 12 Tf 40 700 Td 16 TL\n` +
            lines.map((line) => `(${line.replace(/([()\\])/g, "\\$1")}) Tj T*`).join("\n") +
            `\nET`;
        objects.push(
            `<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Resources<</Font<</F1 3 0 R>>>>/Contents ${5 + page * 2} 0 R>>`
        );
        objects.push(`<</Length ${content.length}>>\nstream\n${content}\nendstream`);
    }

    let pdf = "%PDF-1.4\n";
    const offsets: number[] = [];
    objects.forEach((body, i) => {
        offsets.push(pdf.length);
        pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
    });

    const xrefAt = pdf.length;
    pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
    for (const offset of offsets) pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
    pdf += `trailer<</Size ${objects.length + 1}/Root 1 0 R>>\nstartxref\n${xrefAt}\n%%EOF`;

    return new Uint8Array(Buffer.from(pdf, "latin1"));
}

/**
 * A PDF with a page but no text drawing operations.
 *
 * Stands in for the thing this project actually has to handle: a page of ink
 * exported by an Obsidian handwriting plugin, where the strokes are graphics
 * and there are no characters anywhere in the file.
 */
export function pdfWithoutText(): Uint8Array {
    return pdfWithText([]);
}
