/**
 * Attachment text extraction.
 *
 * The behaviour worth defending here is the distinction between "this document
 * contains no words" and "this document's words are pictures". Those look
 * identical to a naive extractor: both yield an empty string. Conflating them
 * would mean a vault of scanned handwriting reports as indexed and searchable
 * while quietly matching nothing.
 */

import { describe, expect, it } from "vitest";
import { extractAttachment, extractPdf, isImage, isPdf, mimeTypeFor } from "../../src/attachment/extract.js";

/**
 * Build a small, valid PDF containing the given lines as a real text layer.
 *
 * Handwritten rather than generated by a library, so the tests do not depend on
 * a PDF writer whose own output might drift. Offsets are computed so the xref
 * table is correct and strict parsers are satisfied.
 */
function pdfWithText(lines: string[], pages = 1): Uint8Array {
    const objects: string[] = [];

    const pageIds = Array.from({ length: pages }, (_, i) => 4 + i * 2);
    objects.push(`<</Type/Catalog/Pages 2 0 R>>`);
    objects.push(`<</Type/Pages/Kids[${pageIds.map((id) => `${id} 0 R`).join(" ")}]/Count ${pages}>>`);
    objects.push(`<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>`);

    for (let page = 0; page < pages; page++) {
        const content =
            `BT /F1 12 Tf 40 700 Td 16 TL\n` +
            lines.map((line) => `(${line.replace(/([()\\])/g, "\\$1")}) Tj T*`).join("\n") +
            `\nET`;
        objects.push(
            `<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Resources<</Font<</F1 3 0 R>>>>/Contents ${5 + page * 2} 0 R>>`
        );
        objects.push(`<</Length ${content.length}>>\nstream\n${content}\nendstream`);
    }

    let pdf = "%PDF-1.4\n";
    const offsets: number[] = [];
    objects.forEach((body, i) => {
        offsets.push(pdf.length);
        pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
    });

    const xrefAt = pdf.length;
    pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
    for (const offset of offsets) pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
    pdf += `trailer<</Size ${objects.length + 1}/Root 1 0 R>>\nstartxref\n${xrefAt}\n%%EOF`;

    return new Uint8Array(Buffer.from(pdf, "latin1"));
}

/** A PDF with a page but no text drawing operations: a scan, in effect. */
function pdfWithoutText(): Uint8Array {
    return pdfWithText([]);
}

describe("file type detection", () => {
    it("recognises PDFs and images by extension", () => {
        expect(isPdf("Interacts/Notes.pdf")).toBe(true);
        expect(isPdf("notes.PDF")).toBe(true);
        expect(isPdf("notes.md")).toBe(false);
        expect(isImage("photo.JPG")).toBe(true);
        expect(isImage("diagram.svg")).toBe(true);
        expect(isImage("notes.pdf")).toBe(false);
    });

    it("maps extensions to MIME types", () => {
        expect(mimeTypeFor("a.pdf")).toBe("application/pdf");
        expect(mimeTypeFor("a.PNG")).toBe("image/png");
        expect(mimeTypeFor("a.jpeg")).toBe("image/jpeg");
        expect(mimeTypeFor("a.unknown")).toBe("application/octet-stream");
    });
});

describe("PDFs with a text layer", () => {
    it("extracts the text", async () => {
        const result = await extractPdf(
            pdfWithText([
                "Harmony meeting, 2 July 2026.",
                "Discussed the Adelaide office strategy at length.",
                "Actions: confirm the lease, review headcount, report back.",
            ])
        );

        expect(result.outcome).toBe("extracted");
        expect(result.text).toContain("Adelaide office strategy");
        expect(result.pages).toBe(1);
    });

    it("reports the page count", async () => {
        const result = await extractPdf(
            pdfWithText(["Some reasonably long line of text on every page here."], 3)
        );
        expect(result.pages).toBe(3);
        expect(result.outcome).toBe("extracted");
    });

    it("merges the text of several pages", async () => {
        const result = await extractPdf(pdfWithText(["A line long enough to count as real content."], 2));
        const occurrences = result.text.split("A line long enough").length - 1;
        expect(occurrences).toBe(2);
    });
});

describe("PDFs without a text layer", () => {
    it("says so, rather than returning an empty document", async () => {
        const result = await extractPdf(pdfWithoutText());

        expect(result.outcome).toBe("no-text-layer");
        expect(result.reason).toMatch(/no usable text layer/i);
        // The reason must name the cause, since the fix differs entirely.
        expect(result.reason).toMatch(/scan|handwriting|recognition/i);
        expect(result.reason).toMatch(/OCR/);
    });

    it("treats a page with only a stray character as having no text layer", async () => {
        // Scans commonly yield a few characters from a header stamp: enough to
        // look non-empty, nowhere near enough to search.
        const result = await extractPdf(pdfWithText(["p1"]));
        expect(result.outcome).toBe("no-text-layer");
    });
});

describe("failures", () => {
    it("reports an unreadable PDF instead of throwing", async () => {
        const result = await extractPdf(new Uint8Array([1, 2, 3, 4, 5]));
        expect(result.outcome).toBe("failed");
        expect(result.reason).toMatch(/could not read/i);
    });

    it("does not consume the caller's buffer", async () => {
        // The PDF machinery transfers the buffer it is given; a caller that
        // still needs those bytes would otherwise find them gone.
        const bytes = pdfWithText(["A line of genuine content for this test."]);
        const before = bytes.length;
        await extractPdf(bytes);
        expect(bytes.length).toBe(before);
        expect(bytes[0]).toBe("%".charCodeAt(0));
    });
});

describe("non-PDF attachments", () => {
    it("reports images as having nothing to extract, not as a failure", async () => {
        const result = await extractAttachment("photo.png", new Uint8Array([137, 80, 78, 71]));
        expect(result.outcome).toBe("not-textual");
        expect(result.reason).toMatch(/look at it/i);
    });

    it("reports an unsupported type by name", async () => {
        const result = await extractAttachment("archive.zip", new Uint8Array([80, 75]));
        expect(result.outcome).toBe("not-textual");
        expect(result.reason).toMatch(/zip/);
    });
});
